apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: ecommerce
  labels:
    app: mariadb
data:
  my.cnf: |
    [mysqld]
    # Basic settings
    port = 3306
    socket = /var/run/mysqld/mysqld.sock
    pid-file = /var/run/mysqld/mysqld.pid
    
    # Character set
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    
    # InnoDB settings
    innodb_buffer_pool_size = 256M
    innodb_log_file_size = 64M
    innodb_flush_log_at_trx_commit = 2
    innodb_flush_method = O_DIRECT
    
    # Connection settings
    max_connections = 200
    max_connect_errors = 100000
    
    # Query cache
    query_cache_type = 1
    query_cache_size = 32M
    
    # Logging
    log_error = /var/log/mysql/error.log
    slow_query_log = 1
    slow_query_log_file = /var/log/mysql/slow.log
    long_query_time = 2
    
    # Security
    skip-name-resolve
    bind-address = 0.0.0.0
    
    # Performance
    tmp_table_size = 32M
    max_heap_table_size = 32M
    table_open_cache = 2000 