apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  # Cấu hình quyền mặc định
  policy.default: role:admin
  
  # Chính sách RBAC cơ bản
  policy.csv: |
    # Admin có toàn quyền
    p, role:admin, applications, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, clusters, *, *, allow
    
    # Developer có quyền xem và sync ứng dụng
    p, role:developer, applications, get, *, allow
    p, role:developer, applications, sync, *, allow
    p, role:developer, applications, action/*, *, allow
    
    # Reader chỉ có quyền xem
    p, role:reader, applications, get, *, allow 